name: Compile Check CI

on:
  push:
    branches: [ main ]

jobs:
  ubuntu-20:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.1, 10.19, 12.1, 13.2, 14.5, 14.6, 14.15, 15.2]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        working-directory: .
        run: npm install
      
      - name: npm compile
        run: npm run compile

  windows:
    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [10.1, 10.19, 12.1, 13.2, 14.5, 14.6, 14.15, 15.2]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        working-directory: .
        run: npm install
      
      - name: npm compile
        run: npm run compile
        
 
